# Test all formula and casks

# We only want to test on PRs
trigger: none

variables:
  ci: True

pool:
  vmImage: 'macOS-latest'

jobs:
- job: Casks_CI
  steps:
  - script: |
      brew update-reset "$(brew --repository)"
      brew tap wpilibsuite/wpilib
      brew update-reset "$(brew --repository homebrew/cask)"
      brew update-reset "$(brew --repository wpilibsuite/wpilib)"
      brew pull --clean "https://github.com/wpilibsuite/homebrew-wpilib/pull/$(System.PullRequest.PullRequestNumber)"
    displayName: brew pull
  - script: |
      cd "$(brew --repository wpilibsuite/wpilib)"
      brew cask ci
    displayName: brew cask ci
        
- job: Formula_CI
  steps:
  - script: |
      brew update-reset "$(brew --repository)"
      brew update
    displayName: brew pull
  - script: |
      brew test-bot --ci-pr "https://github.com/wpilibsuite/homebrew-wpilib/pull/$(System.PullRequest.PullRequestNumber)"
    displayName: brew test-bot
