# Test all formula and casks

trigger:
  batch: true
  branches:
    include:
    - master

variables:
  ci: True

pool:
  vmImage: 'macOS-latest'

jobs:
  job: Formula Style
    steps:
    - displayName: Check Style
      script: brew style Formula/

  job: Casks CI
    steps:
      script: brew cask ci


  job: Test
    steps:
    - displayName: Test Formula
      script: |
        for f in $( ls ./Formula/*.rb ); do
          brew audit $f
          brew install -v $f
          brew test $f
          brew uninstall $f
        done
